### ISSUE TITLE
The python3 21_reram_simulation_test.py -t sky130 -v --num_banks=1 --num_cols=16 --word_size=16 --num_words=16

### ISSUE THREAD

**Issue by Samarthjainabout** [lekez2005/opennvram-reram#13] opened 2023-05-10 13:51 UTC
The script gets stuck for 3 hours
![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/6d1e8bad-ef5b-4969-9d5c-33c9ec9e6b26)

**Comment by lekez2005** [comment] 2023-05-11 00:57
I'm unable to reproduce this locally. Can you run with -vv instead for a more verbose log? i.e. `python3 21_reram_simulation_test.py -t sky130 -vv --num_banks=1 --num_cols=16 --word_size=16 --num_words=16`. You can attach the log file to a comment for review

**Comment by Samarthjainabout** [comment] 2023-05-11 02:28
The error is weird. says the file is not there but when I check the file using less I can see it in the same path.I have attached the whole log folder as well.

![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/847c5f5b-e002-41e0-a243-ebb91c735370)
[reram_16_c_16_w16.zip](https://github.com/lekez2005/opennvram-reram/files/11447618/reram_16_c_16_w16.zip)

![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/45c7d1e8-d57b-4eb9-abd8-f4251015e129)
![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/774ec504-3be9-4e61-a6f1-46bce7ff5146)

**Comment by lekez2005** [comment] 2023-05-11 03:29
From those logs I can see that the temporary directory wasn't being adequately set when the SCRATCH environment variable is not defined. I have pushed a fix to use `/tmp` if $SCRATCH is not set. Can you test if that works?

**Comment by Samarthjainabout** [comment] 2023-05-11 03:57
after updates still following errors.cant see error in log but warnings
![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/7dae50e2-fce9-4ff0-aef0-0b8bbe288927)
[openram.log](https://github.com/lekez2005/opennvram-reram/files/11447957/openram.log)

**Comment by lekez2005** [comment] 2023-05-11 06:01
Alright, looks like that fixed the previous issue. I'll need to take a closer look at either the magic version or the PDK version. I see you're using magic version 8.3.358 based on the logs while I'm still on 8.3.309. I'll get back to you once I test with version 8.3.358

**Comment by lekez2005** [comment] 2023-05-12 03:19
I have been able to reproduce this bug using magic version 8.3.358. I don't really know what changed to break the extraction scripts. You can use magic [version 8.3.309](https://github.com/RTimothyEdwards/magic/releases/tag/8.3.309) until I further investigate how to correctly use the latest version of magic. 

-- Edited link

**Comment by Samarthjainabout** [comment] 2023-05-12 03:59
its 8.3.309 or 8.3.310?

> I have been able to reproduce this bug using magic version 8.3.358. I don't really know what changed to break the extraction scripts. You can use magic [version 8.3.309](https://github.com/RTimothyEdwards/magic/releases/tag/8.3.310) until I further investigate how to correctly use the latest version of magic.

**Comment by lekez2005** [comment] 2023-05-12 04:53
Yeah, sorry 8.3.309. Edited to reflect the correct link

**Comment by Samarthjainabout** [comment] 2023-05-12 11:14
after changing magic,i get the following error.
![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/ffadee09-a02f-469f-ab95-19f7d8a380e4)

[openram.log](https://github.com/lekez2005/opennvram-reram/files/11463063/openram.log)

**Comment by lekez2005** [comment] 2023-05-13 03:13
Did you modify the sense amp? This step was successfully run in the previous log file you posted which suggests to me that you've modified the sense amplifier

**Comment by Samarthjainabout** [comment] 2023-05-16 09:52
I havent chnaged the sense


> Did you modify the sense amp? This step was successfully run in the previous log file you posted which suggests to me that you've modified the sense amplifier

**Comment by lekez2005** [comment] 2023-05-22 04:00
> I havent chnaged the sense
> 
> > Did you modify the sense amp? This step was successfully run in the previous log file you posted which suggests to me that you've modified the sense amplifier

I suspect the reason this didn't work is because you didn't specify to re-run extractions. By default, extraction is only run if a pex.sp file doesn't already exist since extraction takes a long time. The `--run_pex` explicit flag exists to enforce re-running extraction. FYI, if you make changes, `--run_drc` and `--run_lvs` should also be specified to ensure drc and lvs are run on the newest versions. The full command would look like: `python3 21_reram_simulation_test.py -t sky130 -v --num_banks=1 --num_cols=16 --word_size=16 --num_words=16 --run_drc --run_lvs --run_pex`

**Comment by lekez2005** [comment] 2023-05-22 04:02
> I have been able to reproduce this bug using magic version 8.3.358. I don't really know what changed to break the extraction scripts. You can use magic [version 8.3.309](https://github.com/RTimothyEdwards/magic/releases/tag/8.3.309) until I further investigate how to correctly use the latest version of magic.
> 
> -- Edited link

I found the issue: magic changed the extraction netlist's hierarchy separator in later versions from '/' to '.'. I have pushed changes to fix this so you should be able to use the latest version of magic again

**Comment by Samarthjainabout** [comment] 2023-05-22 06:15
> python3 21_reram_simulation_test.py -t sky130 -v --num_banks=1 --num_cols=16 --word_size=16 --num_words=16 --run_drc --run_lvs --run_pex

after I run this command, it gives same error? 
![image](https://github.com/lekez2005/opennvram-reram/assets/30805083/4e9a0a88-8dc4-4ab4-98c2-428d337a9c52)
[openram.log](https://github.com/lekez2005/opennvram-reram/files/11530575/openram.log)

**Comment by lekez2005** [comment] 2023-05-22 18:10
> > python3 21_reram_simulation_test.py -t sky130 -v --num_banks=1 --num_cols=16 --word_size=16 --num_words=16 --run_drc --run_lvs --run_pex
> 
> after I run this command, it gives same error? ![image](https://user-images.githubusercontent.com/30805083/239818114-4e9a0a88-8dc4-4ab4-98c2-428d337a9c52.png) [openram.log](https://github.com/lekez2005/opennvram-reram/files/11530575/openram.log)

Just realized this is a different error from the one fixed by my magic-related changes. I am unable to reproduce this error from a fresh checkout of the repository. Can you try to reproduce this with a completely clean checkout from the repo? If it still happens, you can also attach the temp.sp spice file in the temp directory?

**Comment by Samarthjainabout** [comment] 2023-05-24 05:55
Hi,
I tried with latest git file and magic version 8.3.358 and got the same error.
PFA Logfiles and temp.sp
[openram.zip](https://github.com/lekez2005/opennvram-reram/files/11550911/openram.zip)

**Comment by lekez2005** [comment] 2023-05-25 06:11
As discussed offline, this issue was because OPENRAM_HOME environment variable was different from the location of the actual code.

**Closed as completed by lekez2005** 2023-05-25 06:11 UTC
